// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student.Web.Api.Data;

#nullable disable

namespace Student.Web.Api.Migrations
{
    [DbContext(typeof(StudentDataContext))]
    [Migration("20231105051503_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Student.Web.Api.Models.Grading", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.HasKey("GradeId");

                    b.ToTable("Gradings", (string)null);
                });

            modelBuilder.Entity("Student.Web.Api.Models.Pupil", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirsName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GradingGradeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.HasIndex("GradingGradeId");

                    b.ToTable("Pupils", (string)null);
                });

            modelBuilder.Entity("Student.Web.Api.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GradingGradeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId");

                    b.HasIndex("GradingGradeId");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("Student.Web.Api.Models.Pupil", b =>
                {
                    b.HasOne("Student.Web.Api.Models.Grading", null)
                        .WithMany("Pupils")
                        .HasForeignKey("GradingGradeId");
                });

            modelBuilder.Entity("Student.Web.Api.Models.Subject", b =>
                {
                    b.HasOne("Student.Web.Api.Models.Grading", null)
                        .WithMany("Subjects")
                        .HasForeignKey("GradingGradeId");
                });

            modelBuilder.Entity("Student.Web.Api.Models.Grading", b =>
                {
                    b.Navigation("Pupils");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
